//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSDoctorsApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDSDoctorsApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Details.
        /// </summary>
        internal static string AddressDetails {
            get {
                return ResourceManager.GetString("AddressDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already registered?.
        /// </summary>
        internal static string Alreadyregistered {
            get {
                return ResourceManager.GetString("Alreadyregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always here for you.
        /// </summary>
        internal static string Alwayshereforyou {
            get {
                return ResourceManager.GetString("Alwayshereforyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Lecturer.
        /// </summary>
        internal static string AssistantLecturer {
            get {
                return ResourceManager.GetString("AssistantLecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate professor.
        /// </summary>
        internal static string Associateprofessor {
            get {
                return ResourceManager.GetString("Associateprofessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachements.
        /// </summary>
        internal static string Attachements {
            get {
                return ResourceManager.GetString("Attachements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Details.
        /// </summary>
        internal static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change password.
        /// </summary>
        internal static string ChangePasswordFailed {
            get {
                return ResourceManager.GetString("ChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat History.
        /// </summary>
        internal static string ChatHistory {
            get {
                return ResourceManager.GetString("ChatHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ChooseaPassword {
            get {
                return ResourceManager.GetString("ChooseaPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a city.
        /// </summary>
        internal static string ChooseCity {
            get {
                return ResourceManager.GetString("ChooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a district.
        /// </summary>
        internal static string ChooseDistrict {
            get {
                return ResourceManager.GetString("ChooseDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ChoosePassword {
            get {
                return ResourceManager.GetString("ChoosePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a specialty.
        /// </summary>
        internal static string ChooseSpecialty {
            get {
                return ResourceManager.GetString("ChooseSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmyourPassword {
            get {
                return ResourceManager.GetString("ConfirmyourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant.
        /// </summary>
        internal static string Consultant {
            get {
                return ResourceManager.GetString("Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Using.
        /// </summary>
        internal static string ContinueUsing {
            get {
                return ResourceManager.GetString("ContinueUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Account.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string Dateofbirth {
            get {
                return ResourceManager.GetString("Dateofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        internal static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this attachment?.
        /// </summary>
        internal static string DeleteAttachment {
            get {
                return ResourceManager.GetString("DeleteAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        internal static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string dir2 {
            get {
                return ResourceManager.GetString("dir2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string dir3 {
            get {
                return ResourceManager.GetString("dir3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Name.
        /// </summary>
        internal static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eDoctor Patient - Login.
        /// </summary>
        internal static string doctouryLogin {
            get {
                return ResourceManager.GetString("doctouryLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Register here.
        /// </summary>
        internal static string Donthaveaccount {
            get {
                return ResourceManager.GetString("Donthaveaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage:.
        /// </summary>
        internal static string Dosage {
            get {
                return ResourceManager.GetString("Dosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duraion:.
        /// </summary>
        internal static string Duraion {
            get {
                return ResourceManager.GetString("Duraion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists.
        /// </summary>
        internal static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the doctor you are looking for.
        /// </summary>
        internal static string EnterDoctorName {
            get {
                return ResourceManager.GetString("EnterDoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP.
        /// </summary>
        internal static string EnterOTP {
            get {
                return ResourceManager.GetString("EnterOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter verification code sent to you email address {0}. If you haven&apos;t received it, please click.
        /// </summary>
        internal static string Enterthecode {
            get {
                return ResourceManager.GetString("Enterthecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Message here.
        /// </summary>
        internal static string EnteryourMessagehere {
            get {
                return ResourceManager.GetString("EnteryourMessagehere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit&apos;s Reason.
        /// </summary>
        internal static string EnteryourReason {
            get {
                return ResourceManager.GetString("EnteryourReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Review.
        /// </summary>
        internal static string EnterYourReview {
            get {
                return ResourceManager.GetString("EnterYourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female Doctors.
        /// </summary>
        internal static string FemaleDoctors {
            get {
                return ResourceManager.GetString("FemaleDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all the required fields.
        /// </summary>
        internal static string FillAllRequiredFields {
            get {
                return ResourceManager.GetString("FillAllRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Career Level.
        /// </summary>
        internal static string FilterByCareerLevel {
            get {
                return ResourceManager.GetString("FilterByCareerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Gender.
        /// </summary>
        internal static string FilterByGender {
            get {
                return ResourceManager.GetString("FilterByGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find A Doctor.
        /// </summary>
        internal static string FindADoctor {
            get {
                return ResourceManager.GetString("FindADoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find By Name.
        /// </summary>
        internal static string FindByName {
            get {
                return ResourceManager.GetString("FindByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find By Specialty.
        /// </summary>
        internal static string FindBySpecialty {
            get {
                return ResourceManager.GetString("FindBySpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the docor you are looking for.
        /// </summary>
        internal static string Findthedocoryouarelookingfor {
            get {
                return ResourceManager.GetString("Findthedocoryouarelookingfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the nearest doctor for you.
        /// </summary>
        internal static string Findthenearestdoctorforyou {
            get {
                return ResourceManager.GetString("Findthenearestdoctorforyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotCredentials {
            get {
                return ResourceManager.GetString("ForgotCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form:.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency:.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Practitioner.
        /// </summary>
        internal static string GeneralPractitioner {
            get {
                return ResourceManager.GetString("GeneralPractitioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here.
        /// </summary>
        internal static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to resend it..
        /// </summary>
        internal static string ifyouhavenotreceived {
            get {
                return ResourceManager.GetString("ifyouhavenotreceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m booking for someone else.
        /// </summary>
        internal static string Imbookingforsomeoneelse {
            get {
                return ResourceManager.GetString("Imbookingforsomeoneelse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        internal static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login.
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigations.
        /// </summary>
        internal static string Investigations {
            get {
                return ResourceManager.GetString("Investigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigations Details.
        /// </summary>
        internal static string InvestigationsDetails {
            get {
                return ResourceManager.GetString("InvestigationsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your data fresh, and updated.
        /// </summary>
        internal static string Keepyourdatafreshandupdated {
            get {
                return ResourceManager.GetString("Keepyourdatafreshandupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Changed Successfully.
        /// </summary>
        internal static string LangChanged {
            get {
                return ResourceManager.GetString("LangChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        internal static string languageSettings {
            get {
                return ResourceManager.GetString("languageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturer.
        /// </summary>
        internal static string Lecturer {
            get {
                return ResourceManager.GetString("Lecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get you back into your account.
        /// </summary>
        internal static string Letsgetyoubackintoyouraccount {
            get {
                return ResourceManager.GetString("Letsgetyoubackintoyouraccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login for doctors appointment booking and medical file management.
        /// </summary>
        internal static string Loginfordoctorsbookingandmedicalfilemanagement {
            get {
                return ResourceManager.GetString("Loginfordoctorsbookingandmedicalfilemanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male Doctors.
        /// </summary>
        internal static string MaleDoctors {
            get {
                return ResourceManager.GetString("MaleDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your bookings and more with a single tap.
        /// </summary>
        internal static string Manageyourbookingsandmorewithasingletap {
            get {
                return ResourceManager.GetString("Manageyourbookingsandmorewithasingletap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication Details.
        /// </summary>
        internal static string MedicationDetails {
            get {
                return ResourceManager.GetString("MedicationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication Name.
        /// </summary>
        internal static string MedicationName {
            get {
                return ResourceManager.GetString("MedicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medications.
        /// </summary>
        internal static string Medications {
            get {
                return ResourceManager.GetString("Medications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will miss you, please come again..
        /// </summary>
        internal static string MissYou {
            get {
                return ResourceManager.GetString("MissYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        internal static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings.
        /// </summary>
        internal static string MyBookings {
            get {
                return ResourceManager.GetString("MyBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Favorite Doctors.
        /// </summary>
        internal static string MyFavoriteDoctors {
            get {
                return ResourceManager.GetString("MyFavoriteDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Date.
        /// </summary>
        internal static string NearestDate {
            get {
                return ResourceManager.GetString("NearestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have bookings to display.
        /// </summary>
        internal static string NoBookings {
            get {
                return ResourceManager.GetString("NoBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have favorite doctors to display.
        /// </summary>
        internal static string NoFavoriteDoctors {
            get {
                return ResourceManager.GetString("NoFavoriteDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization name.
        /// </summary>
        internal static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to confirm OTP code.
        /// </summary>
        internal static string OTPConfirmFailure {
            get {
                return ResourceManager.GetString("OTPConfirmFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP code has been resent.
        /// </summary>
        internal static string OTPResent {
            get {
                return ResourceManager.GetString("OTPResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner name.
        /// </summary>
        internal static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        internal static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 1.
        /// </summary>
        internal static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 2.
        /// </summary>
        internal static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password.
        /// </summary>
        internal static string Pleaseenteryournewpassword {
            get {
                return ResourceManager.GetString("Pleaseenteryournewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        internal static string Professor {
            get {
                return ResourceManager.GetString("Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Saved.
        /// </summary>
        internal static string ProfileSaved {
            get {
                return ResourceManager.GetString("ProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings &amp; Reviews.
        /// </summary>
        internal static string RatingsReviews {
            get {
                return ResourceManager.GetString("RatingsReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register.
        /// </summary>
        internal static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (required).
        /// </summary>
        internal static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        internal static string Reschedule {
            get {
                return ResourceManager.GetString("Reschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESEND.
        /// </summary>
        internal static string RESEND {
            get {
                return ResourceManager.GetString("RESEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-visit your preferred doctors.
        /// </summary>
        internal static string Revisityourpreferreddoctors {
            get {
                return ResourceManager.GetString("Revisityourpreferreddoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Basic Information.
        /// </summary>
        internal static string SaveBasicInformation {
            get {
                return ResourceManager.GetString("SaveBasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule an appointment on the right day for you.
        /// </summary>
        internal static string Scheduleanappointmentontherightdayforyou {
            get {
                return ResourceManager.GetString("Scheduleanappointmentontherightdayforyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Appointment.
        /// </summary>
        internal static string ScheduleAppointment {
            get {
                return ResourceManager.GetString("ScheduleAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        internal static string Schedules {
            get {
                return ResourceManager.GetString("Schedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Cities.
        /// </summary>
        internal static string SearchCities {
            get {
                return ResourceManager.GetString("SearchCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Districts.
        /// </summary>
        internal static string SearchDistricts {
            get {
                return ResourceManager.GetString("SearchDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Specialty.
        /// </summary>
        internal static string SearchSpecialty {
            get {
                return ResourceManager.GetString("SearchSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Gender.
        /// </summary>
        internal static string SelectGender {
            get {
                return ResourceManager.GetString("SelectGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Value.
        /// </summary>
        internal static string SelectValue {
            get {
                return ResourceManager.GetString("SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More.
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in here.
        /// </summary>
        internal static string Signinhere {
            get {
                return ResourceManager.GetString("Signinhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string Sortby {
            get {
                return ResourceManager.GetString("Sortby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialist.
        /// </summary>
        internal static string Specialist {
            get {
                return ResourceManager.GetString("Specialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality.
        /// </summary>
        internal static string Speciality {
            get {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Schedule Request.
        /// </summary>
        internal static string SubmitScheduleRequest {
            get {
                return ResourceManager.GetString("SubmitScheduleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Arabic interface.
        /// </summary>
        internal static string SwitchtoArabicinterface {
            get {
                return ResourceManager.GetString("SwitchtoArabicinterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately.
        /// </summary>
        internal static string Unfortunately {
            get {
                return ResourceManager.GetString("Unfortunately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink your account from this device.
        /// </summary>
        internal static string UnlinkAccount {
            get {
                return ResourceManager.GetString("UnlinkAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        internal static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        internal static string validateEmail {
            get {
                return ResourceManager.GetString("validateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one character should be entered.
        /// </summary>
        internal static string validateName {
            get {
                return ResourceManager.GetString("validateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid OTP code.
        /// </summary>
        internal static string validateOTP {
            get {
                return ResourceManager.GetString("validateOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        internal static string validatePassword {
            get {
                return ResourceManager.GetString("validatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong number, it must start with 0 for local numbers, &amp; 00 for international numbers.
        /// </summary>
        internal static string validatePhone {
            get {
                return ResourceManager.GetString("validatePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Date.
        /// </summary>
        internal static string VisitDate {
            get {
                return ResourceManager.GetString("VisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Reason.
        /// </summary>
        internal static string VisitReason {
            get {
                return ResourceManager.GetString("VisitReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        internal static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search brought up no results. Try using a different keyword..
        /// </summary>
        internal static string Yoursearchbroughtupnoresults {
            get {
                return ResourceManager.GetString("Yoursearchbroughtupnoresults", resourceCulture);
            }
        }
    }
}
