#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSDoctorsApp.HtmlViews2
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "AddExamination.cshtml"
using EDSDoctorsApp.Resources;

#line default
#line hidden

#line 2 "AddExamination.cshtml"
using EDSDoctorsApp;

#line default
#line hidden

#line 3 "AddExamination.cshtml"
using EDSDoctorsApp.Helper.EMR;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "17.1.0.269")]
public partial class AddExamination : AddExaminationBase
{

#line hidden

#line 4 "AddExamination.cshtml"
public List<CustomFieldVM> Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<!DOCTYPE HTML>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"apple-mobile-web-app-capable\"");

WriteLiteral(" content=\"yes\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"apple-mobile-web-app-status-bar-style\"");

WriteLiteral(" content=\"black-translucent\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral("\r\n          content=\"width=device-width, initial-scale=1, minimum-scale=1, maximu" +
"m-scale=1, viewport-fit=cover\"");

WriteLiteral(" />\r\n    <title>eDoctor - New Examination</title>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute ("href", " href=\"", "\""

#line 15 "AddExamination.cshtml"
          , Tuple.Create<string,object,bool> ("", string.Concat("Sticky53/styles/bootstrap",AppResources.dir2,".css")

#line default
#line hidden
, false)
);
WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"Sticky53/fonts/css.css?family=Roboto:300,300i,400,400i,500,500i,700,700i,9" +
"00,900i|Source+Sans+Pro:300,300i,400,400i,600,600i,700,700i,900,900i&display=swa" +
"p\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" href=\"Sticky53/fonts/css/fontawesome-all.min.css\"");

WriteLiteral(">\r\n\r\n    <link");

WriteLiteral(" rel=\"manifest\"");

WriteLiteral(" href=\"_manifest.json\"");

WriteLiteral(" data-pwa-version=\"set_in_manifest_and_pwa_js\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"180x180\"");

WriteLiteral(" href=\"app/icons/icon-192x192.png\"");

WriteLiteral(">\r\n\r\n</head>\r\n\r\n<body");

WriteLiteral(" class=\"theme-light\"");

WriteLiteral(" data-highlight=\"highlight-red\"");

WriteLiteral(" data-gradient=\"body-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"preloader\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"spinner-border color-highlight\"");

WriteLiteral(" role=\"status\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"page\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"header header-fixed header-logo-center \"");

WriteLiteral(" id=\"headerScope\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"header-title\"");

WriteLiteral(">New Examination</a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-back-button");

WriteLiteral(" class=\"header-icon header-icon-1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fas fa-arrow-left\"");

WriteLiteral("></i></a>\r\n            <!-- <a href=\"#\" data-toggle-theme class=\"header-icon head" +
"er-icon-4\"><i class=\"fas fa-lightbulb\"></i></a> -->\r\n        </div>\r\n\r\n        <" +
"div");

WriteLiteral(" class=\"page-content header-clear-medium\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"card card-style\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\" mb-n3 pb-0 text-truncate\"");

WriteLiteral(">");


#line 38 "AddExamination.cshtml"
                                                    Write(App.PatientEMR.PatientsMRNo);


#line default
#line hidden
WriteLiteral("</p>\r\n                    <h2");

WriteLiteral(" class=\" pt-3 pb-3 text-truncate\"");

WriteLiteral(">");


#line 39 "AddExamination.cshtml"
                                                    Write(App.PatientEMR.PatientsName);


#line default
#line hidden
WriteLiteral("</h2>\r\n                    <p");

WriteLiteral(" class=\" font-13 opacity-80 mt-n3\"");

WriteLiteral("><i");

WriteLiteral(" class=\"far fa-calendar\"");

WriteLiteral("></i>");


#line 40 "AddExamination.cshtml"
                                                                                   Write(App.PatientEMR.PatientsDOB);


#line default
#line hidden
WriteLiteral("</p>\r\n                    <p");

WriteLiteral(" class=\" font-13 opacity-80 mt-n3\"");

WriteLiteral("><i");

WriteAttribute ("class", " class=\"", "\""
, Tuple.Create<string,object,bool> ("", "far", true)
, Tuple.Create<string,object,bool> (" ", "fa-", true)

#line 41 "AddExamination.cshtml"
                                    , Tuple.Create<string,object,bool> ("", App.PatientEMR.PatientsGender == "Male" ? "mars" : "venus"

#line default
#line hidden
, false)
);
WriteLiteral("></i>");


#line 41 "AddExamination.cshtml"
                                                                                                                                        Write(App.PatientEMR.PatientsGender);


#line default
#line hidden
WriteLiteral("</p>\r\n                    <p");

WriteLiteral(" class=\" font-13 opacity-80 mt-n3\"");

WriteLiteral("><i");

WriteLiteral(" class=\"far fa-phone\"");

WriteLiteral("></i>");


#line 42 "AddExamination.cshtml"
                                                                                Write(App.PatientEMR.PatientsMobile);


#line default
#line hidden
WriteLiteral("</p>\r\n                    <!-- <p class=\" font-13 opacity-80\"><i class=\"fa fa-map" +
"-marker-alt\"></i> Melbourne, Victoria, Australia Collins Street</p> -->\r\n       " +
"         </div>\r\n            </div>\r\n            <form");

WriteLiteral(" action=\"hybrid:addeditexamination\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"card card-style\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Chief complaint</label>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"HistoryIllness\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">History Of Present Illness</label>\r\n                            <input");

WriteLiteral(" name=\"HistoryIllness\"");

WriteLiteral(" placeholder=\"History Of Present Illness\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"PresentIllness\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Present Illness Onset</label>\r\n                            <select");

WriteLiteral(" id=\"PresentIllness\"");

WriteLiteral(" name=\"PresentIllness\"");

WriteLiteral(">\r\n                                <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Present Illness Onset</option>\r\n                              " +
"  <option");

WriteLiteral(" value=\"Sudden\"");

WriteLiteral(">Sudden</option>\r\n                                <option");

WriteLiteral(" value=\"Acute\"");

WriteLiteral(">Acute</option>\r\n                                <option");

WriteLiteral(" value=\"Gradual\"");

WriteLiteral(">Gradual</option>\r\n                            </select>\r\n                       " +
"     <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"DurationIllness\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Duration Of Present Illness</label>\r\n                            <input");

WriteLiteral(" name=\"DurationIllness\"");

WriteLiteral(" placeholder=\"Duration Of Present Illness\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"Progress\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Progress</label>\r\n                            <select");

WriteLiteral(" id=\"Progress\"");

WriteLiteral(" name=\"Progress\"");

WriteLiteral(">\r\n                                <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Progress</option>\r\n                                <option");

WriteLiteral(" value=\"Progressive\"");

WriteLiteral(">Progressive</option>\r\n                                <option");

WriteLiteral(" value=\"Stationary\"");

WriteLiteral(">Stationary</option>\r\n                                <option");

WriteLiteral(" value=\"Regressive\"");

WriteLiteral(">Regressive</option>\r\n                                <option");

WriteLiteral(" value=\"Fluctuate\"");

WriteLiteral(">Fluctuate</option>\r\n                            </select>\r\n                     " +
"       <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"TypeDuration\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Type of Duration</label>\r\n                            <select");

WriteLiteral(" id=\"TypeDuration\"");

WriteLiteral(" name=\"TypeDuration\"");

WriteLiteral(">\r\n                                <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Type of Duration</option>\r\n                                <op" +
"tion");

WriteLiteral(" value=\"Days\"");

WriteLiteral(">Days</option>\r\n                                <option");

WriteLiteral(" value=\"weeks\"");

WriteLiteral(">Weeks</option>\r\n                                <option");

WriteLiteral(" value=\"month\"");

WriteLiteral(">Month</option>\r\n                                <option");

WriteLiteral(" value=\"year\"");

WriteLiteral(">Year</option>\r\n                            </select>\r\n                          " +
"  <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"New\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">New</label>\r\n                            <input");

WriteLiteral(" name=\"New\"");

WriteLiteral(" placeholder=\"Other\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                 </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"card card-style\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Vital Signs</label>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"BloodPressure\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Blood Pressure</label>\r\n                            <input");

WriteLiteral(" name=\"BloodPressure\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"BloodPressure\"");

WriteLiteral(" placeholder=\"Blood Pressure\"");

WriteLiteral(" />\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"Temperature\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Temperature</label>\r\n                            <input");

WriteLiteral(" name=\"Temperature\"");

WriteLiteral(" onkeypress=\'return event.charCode >= 48 && event.charCode <= 57\'");

WriteLiteral(" type=\"number\"");

WriteLiteral(" id=\"Temperature\"");

WriteLiteral(" placeholder=\"Temperature\"");

WriteLiteral(" />\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"Pulse\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Pulse</label>\r\n                            <input");

WriteLiteral(" name=\"Pulse\"");

WriteLiteral(" onkeypress=\'return event.charCode >= 48 && event.charCode <= 57\'");

WriteLiteral(" type=\"number\"");

WriteLiteral(" id=\"Pulse\"");

WriteLiteral(" placeholder=\"Pulse\"");

WriteLiteral(" />\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"Consciousness\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Consciousness</label>\r\n                            <select");

WriteLiteral(" name=\"Consciousness\"");

WriteLiteral(" id=\"Consciousness\"");

WriteLiteral(">\r\n                                <option");

WriteLiteral(" value=\"\"");

WriteLiteral(" disabled selected>Consciousness</option>\r\n                                <optio" +
"n");

WriteLiteral(" value=\"Alert\"");

WriteLiteral(">Alert</option>\r\n                                <option");

WriteLiteral(" value=\"Confusion\"");

WriteLiteral(">Confusion</option>\r\n                                <option");

WriteLiteral(" value=\"Pain\"");

WriteLiteral(">Pain</option>\r\n                                <option");

WriteLiteral(" value=\"Unresponsive\"");

WriteLiteral(">Unresponsive</option>\r\n                                <option");

WriteLiteral(" value=\"Voice\"");

WriteLiteral(">Voice</option>\r\n                            </select>\r\n                         " +
"   <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"AirOxygen\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Air/Oxygen</label>\r\n                            <select");

WriteLiteral(" name=\"AirOxygen\"");

WriteLiteral(" id=\"Air/Oxygen\"");

WriteLiteral(">\r\n                                <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Air/Oxygen</option>\r\n                                <option");

WriteLiteral(" value=\"Air\"");

WriteLiteral(">Air</option>\r\n                                <option");

WriteLiteral(" value=\"Oxygen\"");

WriteLiteral(">Oxygen</option>\r\n                            </select>\r\n                        " +
"    <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"RespirationRate\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Respiration Rate</label>\r\n                            <input");

WriteLiteral(" name=\"RespirationRate\"");

WriteLiteral(" type=\"number\"");

WriteLiteral(" onkeypress=\'return event.charCode >= 48 && event.charCode <= 57\'");

WriteLiteral(" id=\"RespirationRate\"");

WriteLiteral(" placeholder=\"Respiration Rate\"");

WriteLiteral(" />\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" for=\"SpO2\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">SpO2</label>\r\n                            <input");

WriteLiteral(" name=\"SpO2\"");

WriteLiteral(" type=\"number\"");

WriteLiteral(" onkeypress=\'return event.charCode >= 48 && event.charCode <= 57\'");

WriteLiteral(" id=\"SpO2\"");

WriteLiteral(" placeholder=\"SpO2\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"card card-style\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Examination Notes</label>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"ExaminationNotes\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Examination Notes</label>\r\n                            <input");

WriteLiteral(" name=\"ExaminationNotes\"");

WriteLiteral(" placeholder=\"Examination Notes\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                 </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"card card-style\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Provisional Diagnosis</label>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"ProvisionalDiagnosis\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Provisional Diagnosis</label>\r\n                            <input");

WriteLiteral(" name=\"ProvisionalDiagnosis\"");

WriteLiteral(" placeholder=\"Provisional Diagnosis\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                 </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"card card-style\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Diagnosis</label>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"Diagnosis\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">International Classification Of Disease</label>\r\n                            <se" +
"lect");

WriteLiteral(" id=\"Diagnosis\"");

WriteLiteral(" name=\"Diagnosis\"");

WriteLiteral(" multiple=\"multiple\"");

WriteLiteral(">\r\n                                <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>International Classification Of Disease</option>\r\n            " +
"                    <option");

WriteLiteral(" value=\"Benign recurrent meningitis [Mollaret]\"");

WriteLiteral(">Benign recurrent meningitis [Mollaret]</option>\r\n                               " +
" <option");

WriteLiteral(" value=\"Chronic meningitis\"");

WriteLiteral(">Chronic meningitis</option>\r\n                                <option");

WriteLiteral(" value=\"Meningitis due to other specified causes\"");

WriteLiteral(">Meningitis due to other specified causes</option>\r\n                             " +
"   <option");

WriteLiteral(" value=\"Meningitis, unspecified\"");

WriteLiteral(">Meningitis, unspecified</option>\r\n                                <option");

WriteLiteral(" value=\"Nonpyogenic meningitis\"");

WriteLiteral(">Nonpyogenic meningitis</option>\r\n                            </select>\r\n        " +
"                    <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"DiagnosisNotes\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Diagnosis</label>\r\n                            <input");

WriteLiteral(" name=\"DiagnosisNotes\"");

WriteLiteral(" placeholder=\"Diagnosis\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                 </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"card card-style\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Physiotherapy</label>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"PhysiotherapyTreatments\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Physiotherapy Treatments And Procedures</label>\r\n                            <in" +
"put");

WriteLiteral(" name=\"PhysiotherapyTreatments\"");

WriteLiteral(" placeholder=\"Physiotherapy Treatments And Procedures\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"FrequencySessions\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Frequency Of Sessions</label>\r\n                            <input");

WriteLiteral(" name=\"FrequencySessions\"");

WriteLiteral(" placeholder=\"Frequency Of Sessions\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"Procedures\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Procedures</label>\r\n                            <select");

WriteLiteral(" id=\"Procedures\"");

WriteLiteral(" name=\"Procedures\"");

WriteLiteral(">\r\n                                <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Procedures</option>\r\n                                <option");

WriteLiteral(" value=\"conservative\"");

WriteLiteral(">Conservative</option>\r\n                                <option");

WriteLiteral(" value=\"operative\"");

WriteLiteral(">Operative</option>\r\n                            </select>\r\n                     " +
"       <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"DurationRehabilitation\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Expected Duration Of Rehabilitation</label>\r\n                            <input");

WriteLiteral(" name=\"DurationRehabilitation\"");

WriteLiteral(" placeholder=\"Expected Duration Of Rehabilitation\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"Precautions\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Precautions</label>\r\n                            <input");

WriteLiteral(" name=\"Precautions\"");

WriteLiteral(" placeholder=\"Precautions\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"PhysiotherapyComments\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Comments</label>\r\n                            <input");

WriteLiteral(" name=\"PhysiotherapyComments\"");

WriteLiteral(" placeholder=\"Comments\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"NumberSessions\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Number of Sessions</label>\r\n                            <input");

WriteLiteral(" name=\"NumberSessions\"");

WriteLiteral(" placeholder=\"Number of Sessions\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                 </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"card card-style\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Plan Procedure</label>\r\n                    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"PlanProcedure\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Procedure</label>\r\n                            <input");

WriteLiteral(" name=\"PlanProcedure\"");

WriteLiteral(" placeholder=\"Procedure\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"PlanDate\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Date</label>\r\n                            <input");

WriteLiteral(" type=\"date\"");

WriteLiteral(" style=\"background-color:white;-webkit-appearance: none;\"");

WriteLiteral(" name=\"PlanDate\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"PlanStatus\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Status</label>\r\n                            <select");

WriteLiteral(" id=\"PlanStatus\"");

WriteLiteral(" name=\"PlanStatus\"");

WriteLiteral(">\r\n                                <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Status</option>\r\n                                <option");

WriteLiteral(" value=\"Recommended\"");

WriteLiteral(">Recommended</option>\r\n                                <option");

WriteLiteral(" value=\"Canceled\"");

WriteLiteral(">Canceled</option>\r\n                                <option");

WriteLiteral(" value=\"Completed\"");

WriteLiteral(">Completed</option>\r\n                                <option");

WriteLiteral(" value=\"Conditional\"");

WriteLiteral(">Conditional</option>\r\n                                <option");

WriteLiteral(" value=\"Scheduled\"");

WriteLiteral(">Scheduled</option>\r\n                            </select>\r\n                     " +
"       <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"PlanTime\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Time</label>\r\n                            <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" style=\"background-color:white;-webkit-appearance: none;\"");

WriteLiteral(" name=\"PlanTime\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"Hospital\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Hospital</label>\r\n                            <input");

WriteLiteral(" name=\"Hospital\"");

WriteLiteral(" placeholder=\"Hospital\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"Complications\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Complications</label>\r\n                            <input");

WriteLiteral(" name=\"Complications\"");

WriteLiteral(" placeholder=\"Complications\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"FEES\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Fees</label>\r\n                            <input");

WriteLiteral(" name=\"FEES\"");

WriteLiteral(" placeholder=\"Fees\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"PatientConcerns\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Patient Concerns</label>\r\n                            <input");

WriteLiteral(" name=\"PatientConcerns\"");

WriteLiteral(" placeholder=\"Patient Concerns\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"PlanNotes\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Notes</label>\r\n                            <input");

WriteLiteral(" name=\"PlanNotes\"");

WriteLiteral(" placeholder=\"Notes\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <label");

WriteLiteral(" for=\"SuggestedPrice\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Suggested Price</label>\r\n                            <input");

WriteLiteral(" name=\"SuggestedPrice\"");

WriteLiteral(" placeholder=\"Suggested Price\"");

WriteLiteral(" />\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                            <em></em>\r\n                        </div>\r\n   " +
"                 </div>\r\n                </div>\r\n                <button");

WriteLiteral(" id=\"submit-button\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" data-back-button");

WriteLiteral(" class=\"btn btn-m btn-full mt-4 mb-4 rounded-l shadow-xl bg-highlight font-900 fo" +
"nt-14 text-uppercase w-100\"");

WriteLiteral(">Save</button>\r\n            </form>\r\n        </div>\r\n\r\n\r\n\r\n\r\n    </div>\r\n    <scr" +
"ipt");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"Sticky53/scripts/bootstrap.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"Sticky53/scripts/custom.js\"");

WriteLiteral("></script>\r\n\r\n</body>\r\n");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class AddExaminationBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
