#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSDoctorsApp.HtmlViews2
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "booking.cshtml"
using EDSDoctorsApp.Resources;

#line default
#line hidden

#line 2 "booking.cshtml"
using EDSDoctorsApp.Models;

#line default
#line hidden

#line 3 "booking.cshtml"
using EDSDoctorsApp;

#line default
#line hidden

#line 4 "booking.cshtml"
using Newtonsoft.Json;

#line default
#line hidden

#line 5 "booking.cshtml"
using Newtonsoft.Json.Linq;

#line default
#line hidden

#line 6 "booking.cshtml"
using Xamarin.Essentials;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "17.1.0.269")]
public partial class booking : bookingBase
{

#line hidden

#line 7 "booking.cshtml"
public (List<VisitsVM>,List<VisitsVM>,List<KeyValuePair<string,string>>,int,List<KeyValuePair<string,string>>) Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<!DOCTYPE HTML>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"apple-mobile-web-app-capable\"");

WriteLiteral(" content=\"yes\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"apple-mobile-web-app-status-bar-style\"");

WriteLiteral(" content=\"black-translucent\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral("\r\n          content=\"width=device-width, initial-scale=1, minimum-scale=1, maximu" +
"m-scale=1, viewport-fit=cover\"");

WriteLiteral(" />\r\n    <title>eDoctor - Booking</title>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute ("href", " href=\"", "\""

#line 18 "booking.cshtml"
          , Tuple.Create<string,object,bool> ("", string.Concat("Sticky53/styles/bootstrap",AppResources.dir2,".css")

#line default
#line hidden
, false)
);
WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"Sticky53/fonts/css.css?family=Roboto:300,300i,400,400i,500,500i,700,700i,9" +
"00,900i|Source+Sans+Pro:300,300i,400,400i,600,600i,700,700i,900,900i&display=swa" +
"p\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" href=\"Sticky53/fonts/css/fontawesome-all.min.css\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"manifest\"");

WriteLiteral(" href=\"_manifest.json\"");

WriteLiteral(" data-pwa-version=\"set_in_manifest_and_pwa_js\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"180x180\"");

WriteLiteral(" href=\"Sticky53/app/icons/icon-192x192.png\"");

WriteLiteral(">\r\n</head>\r\n\r\n<body");

WriteLiteral(" class=\"theme-light\"");

WriteLiteral(" data-highlight=\"highlight-red\"");

WriteLiteral(" data-gradient=\"body-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"preloader\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"spinner-border color-highlight\"");

WriteLiteral(" role=\"status\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"page\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"header header-fixed header-logo-center\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"header-title\"");

WriteLiteral(">Bookings</p>\r\n            <a");

WriteLiteral(" href=\"hybrid:goback\"");

WriteLiteral(" data-back-button");

WriteLiteral(" class=\"header-icon header-icon-1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fas fa-arrow-left\"");

WriteLiteral("></i></a>\r\n            <a");

WriteLiteral(" href=\"hybrid:GotoHome\"");

WriteLiteral(" class=\"header-icon header-icon-4\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fas fa-home\"");

WriteLiteral("></i></a>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"page-content header-clear-large\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"card mt-n4\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"tab-controls tabs-small tabs-rounded mt-3\"");

WriteLiteral(" data-highlight=\"bg-orange-dark\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"no-effect d-flex flex-row justify-content-center align-items-center gap-2" +
"\"");

WriteLiteral("\r\n                           data-active");

WriteLiteral(" data-bs-toggle=\"collapse\"");

WriteLiteral(" data-bs-target=\"#TodayTab\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-calendar-day\"");

WriteLiteral("></i> Today Visits\r\n                        </a>\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"no-effect d-flex flex-row justify-content-center align-items-center gap-2" +
"\"");

WriteLiteral("\r\n                           data-bs-toggle=\"collapse\"");

WriteLiteral(" data-bs-target=\"#AllTab\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-history\"");

WriteLiteral("></i>All Visits</a>\r\n                    </div>\r\n                </div>\r\n        " +
"    </div>\r\n            <!-- Tabs content Group -->\r\n            <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(" id=\"tab-group-3\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"clearfix mb-3\"");

WriteLiteral("></div>\r\n                <!-- Tabs 1 -->\r\n                <div");

WriteLiteral(" data-bs-parent=\"#tab-group-3\"");

WriteLiteral(" class=\"collapse show\"");

WriteLiteral(" id=\"TodayTab\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"search-box bg-white rounded-xl bottom-0\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i>\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"border-0\"");

WriteLiteral(" placeholder=\"Search here..\"");

WriteLiteral(" id=\"TodaySearch\"");

WriteAttribute ("onkeyup", " onkeyup=\"", "\""
, Tuple.Create<string,object,bool> ("", "Search(this,", true)

#line 56 "booking.cshtml"
                                                                                       , Tuple.Create<string,object,bool> ("", App.LoadMoreBookingsRequest1

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ",", true)

#line 56 "booking.cshtml"
                                                                                                                     , Tuple.Create<string,object,bool> ("", App.TotalPages

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ",\'", true)

#line 56 "booking.cshtml"
                                                                                                                                      , Tuple.Create<string,object,bool> ("", SecureStorage.GetAsync("userToken").Result

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\',Get_SelectedTab())", true)
);
WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"clear-search disabled mt-0 me-5\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-times color-red-dark\"");

WriteLiteral("></i>\r\n                        </a>\r\n\r\n                        <a");

WriteLiteral(" data-menu=\"menu-sidebar-left-1\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-filter color-dark-light font-12\"");

WriteLiteral("></i>\r\n                        </a>\r\n\r\n                    </div>\r\n              " +
"      <div");

WriteLiteral(" class=\"BookingContent\"");

WriteLiteral(">\r\n                        <!--  -->\r\n                        <div");

WriteLiteral(" class=\"search-results disabled-search-list-XX\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"list-group list-custom-large\"");

WriteLiteral(">\r\n                                <!-- With 2 btn -->\r\n");


#line 71 "booking.cshtml"
                                

#line default
#line hidden

#line 71 "booking.cshtml"
                                 foreach (var VisitPatient in Model.Item1)
                                {


#line default
#line hidden
WriteLiteral("                                    <div");

WriteLiteral(" class=\"card card-style mt-5 overflow-visible\"");

WriteLiteral(" style=\"margin:0\"");

WriteLiteral(" data-filter-item");

WriteLiteral("\r\n                                     data-filter-name=\"all\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"row mb-0\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"col-9\"");

WriteLiteral(">\r\n                                                    <p>\r\n                     " +
"                                   <h6");

WriteLiteral(" class=\"color-gray-dark mb-n3\"");

WriteLiteral(">");


#line 79 "booking.cshtml"
                                                                                     Write(VisitPatient.VisitsSndep);


#line default
#line hidden
WriteLiteral("</h6>\r\n                                                        <h4");

WriteLiteral(" class=\"color-dark-light font-700 font-22 mt-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                            ");


#line 81 "booking.cshtml"
                                                       Write(VisitPatient.VisitsbookingPatientName);


#line default
#line hidden
WriteLiteral("\r\n                                                        </h4>\r\n                " +
"                                    </p>\r\n                                      " +
"              <h5>\r\n                                                        <spa" +
"n");

WriteLiteral(" class=\"me-3\"");

WriteLiteral(">\r\n                                                            <span>\r\n          " +
"                                                      <b>");


#line 87 "booking.cshtml"
                                                              Write(VisitPatient.VisitsStatus);


#line default
#line hidden
WriteLiteral(@"</b>
                                                            </span>
                                                        </span>
                                                    </h5>
                                                    <h5>
                                                        <span");

WriteLiteral(" class=\"me-3\"");

WriteLiteral(">\r\n                                                            <span");

WriteLiteral(" class=\"fa fa-clock\"");

WriteLiteral("></span>\r\n                                                            <span>\r\n   " +
"                                                             <b>");


#line 95 "booking.cshtml"
                                                              Write(VisitPatient.VisitsScheduleDateTime);


#line default
#line hidden
WriteLiteral(@"</b>
                                                            </span>
                                                        </span>
                                                    </h5>
                                                    <h5>
                                                        <span");

WriteLiteral(" class=\"me-3\"");

WriteLiteral(">\r\n                                                            <span");

WriteLiteral(" class=\"fa fa-map-pin me-3 font-11\"");

WriteLiteral("></span>\r\n                                                            <span>\r\n   " +
"                                                             <b>");


#line 103 "booking.cshtml"
                                                              Write(VisitPatient.VisitLocation);


#line default
#line hidden
WriteLiteral(@"</b>
                                                            </span>
                                                        </span>
                                                    </h5>
                                                </div>
                                                <p>
                                                    <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">\r\n                                                        <div");

WriteLiteral(" class=\"d-flex flex-row gap-1 justify-content-end\"");

WriteLiteral(">\r\n                                                            <a");

WriteAttribute ("href", " href=\"", "\""
, Tuple.Create<string,object,bool> ("", "hybrid:gotopatientsemrfrombooking?PatientID=", true)

#line 111 "booking.cshtml"
                                                                          , Tuple.Create<string,object,bool> ("", VisitPatient.VisitsPatientsId

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "&PatientName=", true)

#line 111 "booking.cshtml"
                                                                                                                     , Tuple.Create<string,object,bool> ("", VisitPatient.VisitsbookingPatientName

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "&PatientMRno=", true)

#line 111 "booking.cshtml"
                                                                                                                                                                        , Tuple.Create<string,object,bool> ("", VisitPatient.VisitsSndep

#line default
#line hidden
, false)
);
WriteLiteral("\r\n                                                           class=\"btn rounded-m" +
" bg-dark-dark font-700 text-uppercase line-height-sm\"");

WriteLiteral(">Details</a>\r\n                                                        </div>\r\n   " +
"                                                     ");

WriteLiteral(@"
                                                    </div>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
");


#line 129 "booking.cshtml"
                                }


#line default
#line hidden
WriteLiteral("                            </div>\r\n");


#line 131 "booking.cshtml"
                            

#line default
#line hidden

#line 131 "booking.cshtml"
                             if (App.TotalBookingsPages1 > 1)
                            {


#line default
#line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                                    <a");

WriteLiteral(" class=\"w-100 btn rounded-m bg-highlight font-700 text-uppercase line-height-sm\"");

WriteLiteral(" id=\"TodayVisitsShowMoreBtn\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "GetResources(", true)

#line 134 "booking.cshtml"
                                                                                                                                  , Tuple.Create<string,object,bool> ("", App.LoadMoreBookingsRequest1

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ",", true)

#line 134 "booking.cshtml"
                                                                                                                                                                , Tuple.Create<string,object,bool> ("", App.TotalBookingsPages1

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ",\'", true)

#line 134 "booking.cshtml"
                                                                                                                                                                                          , Tuple.Create<string,object,bool> ("", SecureStorage.GetAsync("userToken").Result

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\',\'TodayVisits\',GetSearchTerm(\'TodaySearch\'))", true)
);
WriteLiteral(">");


#line 134 "booking.cshtml"
                                                                                                                                                                                                                                                                                                                      Write(AppResources.ShowMore);


#line default
#line hidden
WriteLiteral("</a>\r\n                                </div>\r\n");


#line 136 "booking.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                            \r\n                                <div");

WriteLiteral(" id=\"TodayNoSearch\"");

WriteAttribute ("class", " class=\"", "\""
, Tuple.Create<string,object,bool> ("", "search-no-results", true)
, Tuple.Create<string,object,bool> (" ", new Action<System.IO.TextWriter> (__razor_attribute_value_writer => {

#line 138 "booking.cshtml"
                                                                                  if (App.TotalBookingsPages1 > 0)
                            {

#line default
#line hidden
WriteLiteralTo(__razor_attribute_value_writer, "disabled");


#line 139 "booking.cshtml"
                                                  }

#line default
#line hidden
}), false)
, Tuple.Create<string,object,bool> (" ", "mt-4", true)
);
WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"card card-style\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">
                                            <h1>No Results</h1>
                                            <p>
                                                No Records Found.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
                <!-- Tab 2 -->
                <div");

WriteLiteral(" data-bs-parent=\"#tab-group-3\"");

WriteLiteral(" class=\"collapse\"");

WriteLiteral(" id=\"AllTab\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"search-box bg-white rounded-xl bottom-0\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i>\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"border-0\"");

WriteLiteral(" placeholder=\"Search here..\"");

WriteLiteral(" id=\"AllSearch\"");

WriteAttribute ("onkeyup", " onkeyup=\"", "\""
, Tuple.Create<string,object,bool> ("", "Search(this,", true)

#line 156 "booking.cshtml"
                                                                                     , Tuple.Create<string,object,bool> ("", App.LoadMoreBookingsRequest2

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ",", true)

#line 156 "booking.cshtml"
                                                                                                                   , Tuple.Create<string,object,bool> ("", App.TotalPages

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ",\'", true)

#line 156 "booking.cshtml"
                                                                                                                                    , Tuple.Create<string,object,bool> ("", SecureStorage.GetAsync("userToken").Result

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\',Get_SelectedTab())", true)
);
WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"clear-search disabled mt-0 me-5\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-times color-red-dark\"");

WriteLiteral("></i>\r\n                        </a>\r\n\r\n                        <a");

WriteLiteral(" data-menu=\"menu-sidebar-left-1\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-filter color-dark-light font-12\"");

WriteLiteral("></i>\r\n                        </a>\r\n\r\n                    </div>\r\n              " +
"      <div");

WriteLiteral(" class=\"BookingContent2\"");

WriteLiteral(">\r\n                        <!-- With 2 btn -->\r\n");


#line 168 "booking.cshtml"
                        

#line default
#line hidden

#line 168 "booking.cshtml"
                         foreach (var VisitPatient in Model.Item2)
                        {


#line default
#line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"card card-style mt-5 overflow-visible\"");

WriteLiteral(" style=\"margin:0\"");

WriteLiteral(" data-filter-item");

WriteLiteral("\r\n                             data-filter-name=\"all\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"row mb-0\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"col-9\"");

WriteLiteral(">\r\n                                            <p>\r\n                             " +
"                   <h6");

WriteLiteral(" class=\"color-gray-dark mb-n3\"");

WriteLiteral(">");


#line 176 "booking.cshtml"
                                                                             Write(VisitPatient.VisitsSndep);


#line default
#line hidden
WriteLiteral("</h6>\r\n                                                <h4");

WriteLiteral(" class=\"color-dark-light font-700 font-22 mt-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");


#line 178 "booking.cshtml"
                                               Write(VisitPatient.VisitsbookingPatientName);


#line default
#line hidden
WriteLiteral("\r\n                                                </h4>\r\n                        " +
"                    </p>\r\n                                            <h5>\r\n    " +
"                                            <span");

WriteLiteral(" class=\"me-3\"");

WriteLiteral(">\r\n                                                    <span>\r\n                  " +
"                                      <b>");


#line 184 "booking.cshtml"
                                                      Write(VisitPatient.VisitsStatus);


#line default
#line hidden
WriteLiteral(@"</b>
                                                    </span>
                                                </span>
                                            </h5>
                                            <h5>
                                                <span");

WriteLiteral(" class=\"me-3\"");

WriteLiteral(">\r\n                                                    <span");

WriteLiteral(" class=\"fa fa-clock\"");

WriteLiteral("></span>\r\n                                                    <span>\r\n           " +
"                                             <b>");


#line 192 "booking.cshtml"
                                                      Write(VisitPatient.VisitsScheduleDateTime);


#line default
#line hidden
WriteLiteral(@"</b>
                                                    </span>
                                                </span>
                                            </h5>
                                            <h5>
                                                <span");

WriteLiteral(" class=\"me-3\"");

WriteLiteral(">\r\n                                                    <span");

WriteLiteral(" class=\"fa fa-map-pin me-3 font-11\"");

WriteLiteral("></span>\r\n                                                    <span>\r\n           " +
"                                             <b>");


#line 200 "booking.cshtml"
                                                      Write(VisitPatient.VisitLocation);


#line default
#line hidden
WriteLiteral(@"</b>
                                                    </span>
                                                </span>
                                            </h5>
                                        </div>
                                        <p>
                                            <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"d-flex flex-row gap-1 justify-content-end\"");

WriteLiteral(">\r\n                                                    <a");

WriteAttribute ("href", " href=\"", "\""
, Tuple.Create<string,object,bool> ("", "hybrid:gotopatientsemrfrombooking?PatientID=", true)

#line 208 "booking.cshtml"
                                                                  , Tuple.Create<string,object,bool> ("", VisitPatient.VisitsPatientsId.ToString()

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "&PatientName=", true)

#line 208 "booking.cshtml"
                                                                                                                        , Tuple.Create<string,object,bool> ("", VisitPatient.VisitsbookingPatientName

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "&PatientMRno=", true)

#line 208 "booking.cshtml"
                                                                                                                                                                           , Tuple.Create<string,object,bool> ("", VisitPatient.VisitsSndep

#line default
#line hidden
, false)
);
WriteLiteral("\r\n                                                   class=\"btn rounded-m bg-dark" +
"-dark font-700 text-uppercase line-height-sm\"");

WriteLiteral(">Details</a>\r\n                                                </div>\r\n           " +
"                                     ");

WriteLiteral("\r\n                                            </div>\r\n                           " +
"             </p>\r\n                                    </div>\r\n                 " +
"               </div>\r\n                            </div>\r\n");


#line 226 "booking.cshtml"
                        }


#line default
#line hidden
WriteLiteral("                    </div>\r\n                    <!-- btn Load more -->\r\n");


#line 229 "booking.cshtml"
                    

#line default
#line hidden

#line 229 "booking.cshtml"
                     if (App.TotalBookingsPages2 > 1)
                    {


#line default
#line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" class=\"w-100 btn rounded-m bg-highlight font-700 text-uppercase line-height-sm\"");

WriteLiteral(" id=\"AllVisitsShowMoreBtn\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "GetResources(", true)

#line 232 "booking.cshtml"
                                                                                                                        , Tuple.Create<string,object,bool> ("", App.LoadMoreBookingsRequest2

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ",", true)

#line 232 "booking.cshtml"
                                                                                                                                                      , Tuple.Create<string,object,bool> ("", App.TotalBookingsPages2

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ",\'", true)

#line 232 "booking.cshtml"
                                                                                                                                                                                , Tuple.Create<string,object,bool> ("", SecureStorage.GetAsync("userToken").Result

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\',\'AllVisits\',GetSearchTerm(\'AllSearch\'))", true)
);
WriteLiteral(">");


#line 232 "booking.cshtml"
                                                                                                                                                                                                                                                                                                        Write(AppResources.ShowMore);


#line default
#line hidden
WriteLiteral("</a>\r\n                        </div>\r\n");


#line 234 "booking.cshtml"
                    }


#line default
#line hidden
WriteLiteral("                    <div");

WriteLiteral(" id=\"AllNoSearch\"");

WriteAttribute ("class", " class=\"", "\""
, Tuple.Create<string,object,bool> ("", "search-no-results", true)
, Tuple.Create<string,object,bool> (" ", new Action<System.IO.TextWriter> (__razor_attribute_value_writer => {

#line 235 "booking.cshtml"
                                                                    if (App.TotalBookingsPages2 > 0)
                            {

#line default
#line hidden
WriteLiteralTo(__razor_attribute_value_writer, "disabled");


#line 236 "booking.cshtml"
                                                  }

#line default
#line hidden
}), false)
, Tuple.Create<string,object,bool> (" ", "mt-4", true)
);
WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"card card-style\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">
                                    <h1>No Results</h1>
                                    <p>
                                        No Records Found.
                                    </p>
                                </div>
                            </div>
                        </div>
                </div>
            </div>




        </div>

        <!-- SideBar -->
        <div");

WriteLiteral(" id=\"menu-sidebar-left-1\"");

WriteLiteral(" class=\"bg-white menu menu-box-left d-flex flex-column\"");

WriteLiteral(" data-menu-width=\"310\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"me-3 ms-3\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"text-uppercase font-900 font-11 color-orange-dark\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-sort px-2 mt-4 pb-3\"");

WriteLiteral("></i>Sort by\r\n                </span>\r\n                <div");

WriteLiteral(" class=\"list-group list-custom-small list-icon-0\"");

WriteLiteral(">\r\n\r\n                    <!-- Filter By location -->\r\n                    <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-map-pin mt-n3\"");

WriteLiteral("></i>\r\n                        <label");

WriteLiteral(" for=\"\"");

WriteLiteral(" class=\"color-highlight \"");

WriteLiteral(">Sort By location</label>\r\n                        <select");

WriteLiteral(" id=\"\"");

WriteLiteral(" class=\"mt-3\"");

WriteLiteral(" style=\"background-color:white;-webkit-appearance: none\"");

WriteLiteral(" onchange=\"this.options[this.selectedIndex].value && (window.location = \'hybrid:d" +
"osortbooking?sortby=Location&sort=\' + this.options[this.selectedIndex].value);\"");

WriteLiteral(">\r\n                            <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Sort By location</option>\r\n");


#line 269 "booking.cshtml"
                            

#line default
#line hidden

#line 269 "booking.cshtml"
                             foreach (var location in Model.Item5)
                            {


#line default
#line hidden
WriteLiteral("                                <option");

WriteAttribute ("value", " value=\"", "\""

#line 271 "booking.cshtml"
        , Tuple.Create<string,object,bool> ("", location.Value

#line default
#line hidden
, false)
);
WriteLiteral(">");


#line 271 "booking.cshtml"
                                                           Write(location.Value);


#line default
#line hidden
WriteLiteral("</option>\r\n");


#line 272 "booking.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                        </select>\r\n                        <span");

WriteLiteral(" class=\"mt-n4\"");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                    </div>\r\n\r\n                    <!-- Sort By Stat" +
"us -->\r\n                    <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-flag-checkered mt-n3\"");

WriteLiteral("></i>\r\n                        <label");

WriteLiteral(" for=\"\"");

WriteLiteral(" class=\"color-highlight \"");

WriteLiteral(">Sort By Status</label>\r\n                        <select");

WriteLiteral(" id=\"\"");

WriteLiteral(" class=\"mt-3\"");

WriteLiteral(" style=\"background-color:white;-webkit-appearance: none\"");

WriteLiteral(" onchange=\"this.options[this.selectedIndex].value && (window.location = \'hybrid:d" +
"osortbooking?sortby=VisitsStatus&sort=\' + this.options[this.selectedIndex].value" +
");\"");

WriteLiteral(">\r\n                            <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Sort By Status</option>\r\n");


#line 283 "booking.cshtml"
                            

#line default
#line hidden

#line 283 "booking.cshtml"
                             foreach (var status in Model.Item3)
                            {


#line default
#line hidden
WriteLiteral("                                <option");

WriteAttribute ("value", " value=\"", "\""

#line 285 "booking.cshtml"
        , Tuple.Create<string,object,bool> ("", status.Key

#line default
#line hidden
, false)
);
WriteLiteral(">");


#line 285 "booking.cshtml"
                                                       Write(status.Value);


#line default
#line hidden
WriteLiteral("</option>\r\n");


#line 286 "booking.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                        </select>\r\n                        <span");

WriteLiteral(" class=\"mt-n4\"");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                    </div>\r\n\r\n                </div>\r\n            <" +
"/div>\r\n        </div>\r\n\r\n        <!--  -->\r\n\r\n\r\n    </div>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"Sticky53/scripts/bootstrap.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"Sticky53/scripts/custom.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"Sticky/scripts/SearchResults.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"Sticky/scripts/EDS.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"Sticky/scripts/jquery-3.6.0.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        function Get_SelectedTab()
        {
            var TabID = document.querySelector('.show').id;
            if(TabID == ""TodayTab"")
            return ""TodayVisits"";
            else if (TabID == ""AllTab"")
            return ""AllVisits"";
        }
        function GetSearchTerm(sender){
            return document.getElementById(sender).value;
        }
        function Get_SelectedRequest()
        {
            debugger;
            var TabID = document.querySelector('.show').id;
            if(TabID == ""TodayTab"")
            return decodeHtml(""");


#line 322 "booking.cshtml"
                          Write(App.LoadMoreBookingsRequest1);


#line default
#line hidden
WriteLiteral("\");\r\n            else if (TabID == \"AllTab\")\r\n            return decodeHtml(\"");


#line 324 "booking.cshtml"
                          Write(App.LoadMoreBookingsRequest2);


#line default
#line hidden
WriteLiteral("\");\r\n        }\r\n        function decodeHtml(html) {\r\n            debugger;\r\n     " +
"       var txt = document.createElement(\"textarea\");\r\n            txt.innerHTML " +
"= html;\r\n            return txt.value;\r\n        }\r\n    </script>\r\n\r\n</body>\r\n</h" +
"tml>\r\n");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class bookingBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
