#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSDoctorsApp.HtmlViews2
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "compeletProfileWithoutModal.cshtml"
using EDSDoctorsApp.Resources;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "17.1.0.324")]
public partial class compeletProfileWithoutModal : compeletProfileWithoutModalBase
{

#line hidden

public override void Execute()
{
WriteLiteral("<!DOCTYPE HTML>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"apple-mobile-web-app-capable\"");

WriteLiteral(" content=\"yes\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"apple-mobile-web-app-status-bar-style\"");

WriteLiteral(" content=\"black-translucent\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral("\r\n        content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-" +
"scale=1, viewport-fit=cover\"");

WriteLiteral(" />\r\n    <title>eDoctor | Compelet profile data</title>\r\n   <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute ("href", " href=\"", "\""

#line 12 "compeletProfileWithoutModal.cshtml"
         , Tuple.Create<string,object,bool> ("", string.Concat("Sticky53/styles/bootstrap",AppResources.dir2,".css")

#line default
#line hidden
, false)
);
WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"Sticky53/fonts/css.css?family=Roboto:300,300i,400,400i,500,500i,700,700i,9" +
"00,900i|Source+Sans+Pro:300,300i,400,400i,600,600i,700,700i,900,900i&display=swa" +
"p\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" href=\"Sticky53/fonts/css/fontawesome-all.min.css\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"manifest\"");

WriteLiteral(" href=\"_manifest.json\"");

WriteLiteral(" data-pwa-version=\"set_in_manifest_and_pwa_js\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"180x180\"");

WriteLiteral(" href=\"app/icons/icon-192x192.png\"");

WriteLiteral(">\r\n</head>\r\n\r\n<body");

WriteLiteral(" class=\"theme-light\"");

WriteLiteral(" data-highlight=\"highlight-red\"");

WriteLiteral(" data-gradient=\"body-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"preloader\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"spinner-border color-highlight\"");

WriteLiteral(" role=\"status\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"page\"");

WriteLiteral(">\r\n        <!-- Header -->\r\n        <div");

WriteLiteral(" class=\"header header-fixed header-logo-center\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"index.html\"");

WriteLiteral(" class=\"header-title\"");

WriteLiteral(">Compelete prfile data</a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-back-button");

WriteLiteral(" class=\"header-icon header-icon-1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fas fa-arrow-left\"");

WriteLiteral("></i></a>\r\n            <!-- <a href=\"#\" data-toggle-theme class=\"header-icon head" +
"er-icon-4\"><i class=\"fas fa-lightbulb\"></i></a> -->\r\n        </div>\r\n        <!-" +
"- Footer -->\r\n\r\n        <!-- Page Content -->\r\n        <div");

WriteLiteral(" class=\"page-content header-clear-large\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"card card-style\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n\r\n\r\n\r\n\r\n                    <form");

WriteLiteral(" id=\"regForm\"");

WriteLiteral(" action=\"\"");

WriteLiteral(">\r\n                        <!-- Steper -->\r\n                        <div");

WriteLiteral(" class=\"d-flex pb-3 mb-n4\"");

WriteLiteral(">\r\n\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"width:35px; line-height:35px;\"");

WriteLiteral("\r\n                                class=\"me-auto font-600 rounded-l text-center s" +
"tep bg-gray-light\"");

WriteLiteral("><i\r\n                                    class=\"fa fa-user-nurse\"></i></a>\r\n     " +
"                       <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"width:35px; line-height:35px;\"");

WriteLiteral("\r\n                                class=\"m-auto font-600 rounded-l text-center st" +
"ep bg-gray-light\"");

WriteLiteral("><i\r\n                                    class=\"fa fa-address-card\"></i></a>\r\n   " +
"                         <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"width:35px; line-height:35px;\"");

WriteLiteral("\r\n                                class=\"ms-auto font-600 rounded-l text-center s" +
"tep bg-gray-light\"");

WriteLiteral("><i\r\n                                    class=\"fa fa-check-circle\"></i></a>\r\n   " +
"                     </div>\r\n                        <div");

WriteLiteral(" class=\"divider position-absolute start-0 end-0 mt-n2\"");

WriteLiteral(" style=\"z-index:-1;\"");

WriteLiteral("></div>\r\n\r\n                        <div");

WriteLiteral(" class=\"tab\"");

WriteLiteral(">\r\n                            <h1");

WriteLiteral(" class=\"pt-4 mt-3 mb-n1\"");

WriteLiteral(">Compelet you Basic Data</h1>\r\n                            <p");

WriteLiteral(" class=\"px-2\"");

WriteLiteral(">Please fill all data</p>\r\n                            <!-- Name -->\r\n           " +
"                 <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-user\"");

WriteLiteral("></i>\r\n                                <input");

WriteLiteral(" type=\"name\"");

WriteLiteral(" class=\"form-control validate-name\"");

WriteLiteral(" id=\"form1a\"");

WriteLiteral(" placeholder=\"Name\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"form1a\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Name</label>\r\n                                <i");

WriteLiteral(" class=\"fa fa-times disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                                <em>(required)</em>\r\n                     " +
"       </div>\r\n                            <!-- Name .. -->\r\n                   " +
"         <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-user\"");

WriteLiteral("></i>\r\n                                <input");

WriteLiteral(" type=\"name\"");

WriteLiteral(" class=\"form-control validate-name\"");

WriteLiteral(" id=\"form1b\"");

WriteLiteral(" placeholder=\"Name..\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"form1b\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Name(..)</label>\r\n                                <i");

WriteLiteral(" class=\"fa fa-times disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                            </div>\r\n                            <!-- SELEC" +
"T A GENDER -->\r\n                            <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-venus-mars\"");

WriteLiteral("></i>\r\n                                <label");

WriteLiteral(" for=\"form1c\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Select Gender</label>\r\n                                <select");

WriteLiteral(" id=\"form1c\"");

WriteLiteral(">\r\n                                    <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Select Gender</option>\r\n                                    <o" +
"ption");

WriteLiteral(" value=\"\"");

WriteLiteral(">Gender 1</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Gender 2</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Gender 3</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Gender 4</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Gender 5</option>\r\n                                </select>\r\n                  " +
"              <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                                <em></em>\r\n                            </d" +
"iv>\r\n                            <!-- SELECT DEGREE -->\r\n                       " +
"     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-graduation-cap\"");

WriteLiteral("></i>\r\n                                <label");

WriteLiteral(" for=\"form1d\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Select degree</label>\r\n                                <select");

WriteLiteral(" id=\"form1d\"");

WriteLiteral(">\r\n                                    <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Select degree</option>\r\n                                    <o" +
"ption");

WriteLiteral(" value=\"\"");

WriteLiteral(">degree 1</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">degree 2</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">degree 3</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">degree 4</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">degree 5</option>\r\n                                </select>\r\n                  " +
"              <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                                <em></em>\r\n                            </d" +
"iv>\r\n                            <!-- SELECT specialist -->\r\n                   " +
"         <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-user-tag\"");

WriteLiteral("></i>\r\n                                <label");

WriteLiteral(" for=\"form1e\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Select specialist</label>\r\n                                <select");

WriteLiteral(" id=\"form1e\"");

WriteLiteral(">\r\n                                    <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Select specialist</option>\r\n                                  " +
"  <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">specialist 1</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">specialist 2</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">specialist 3</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">specialist 4</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">specialist 5</option>\r\n                                </select>\r\n              " +
"                  <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                                <em></em>\r\n                            </d" +
"iv>\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"tab\"");

WriteLiteral(">\r\n                            <h1");

WriteLiteral(" class=\"pt-4 mt-3 mb-n1\"");

WriteLiteral(">Compelet you address</h1>\r\n                            <p");

WriteLiteral(" class=\"px-2\"");

WriteLiteral(">Please fill all data</p>\r\n                            <!-- SELECT  Country -->\r\n" +
"                            <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-city\"");

WriteLiteral("></i>\r\n                                <label");

WriteLiteral(" for=\"form1f\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Select Country</label>\r\n                                <select");

WriteLiteral(" id=\"form1f\"");

WriteLiteral(">\r\n                                    <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Select Country</option>\r\n                                    <" +
"option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Country</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Country 1</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Country 2</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Country 3</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">Country 4</option>\r\n                                </select>\r\n                 " +
"               <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                                <em>(required)</em>\r\n                     " +
"       </div>\r\n                            <!-- SELECT  City -->\r\n              " +
"              <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-location-arrow\"");

WriteLiteral("></i>\r\n                                <label");

WriteLiteral(" for=\"form1g\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Select City</label>\r\n                                <select");

WriteLiteral(" id=\"form1g\"");

WriteLiteral(">\r\n                                    <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Select City</option>\r\n                                    <opt" +
"ion");

WriteLiteral(" value=\"\"");

WriteLiteral(">City 1</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">City 2</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">City 3</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">City 4</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">City 5</option>\r\n                                </select>\r\n                    " +
"            <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                                <em>(required)</em>\r\n                     " +
"       </div>\r\n                            <!-- SELECT  district -->\r\n          " +
"                  <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-map-marked\"");

WriteLiteral("></i>\r\n                                <label");

WriteLiteral(" for=\"form1h\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Select district</label>\r\n                                <select");

WriteLiteral(" id=\"form1h\"");

WriteLiteral(">\r\n                                    <option");

WriteLiteral(" value=\"default\"");

WriteLiteral(" disabled selected>Select district</option>\r\n                                    " +
"<option");

WriteLiteral(" value=\"\"");

WriteLiteral(">district 1</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">district 2</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">district 3</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">district 4</option>\r\n                                    <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">district 5</option>\r\n                                </select>\r\n                " +
"                <span");

WriteLiteral(" style=\"width:8.75px;height:60%;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral("></i></span>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                                <em></em>\r\n                            </d" +
"iv>\r\n                            <!-- Building N.O. -->\r\n                       " +
"     <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-building\"");

WriteLiteral("></i>\r\n                                <input");

WriteLiteral(" type=\"name\"");

WriteLiteral(" class=\"form-control validate-name\"");

WriteLiteral(" id=\"form1i\"");

WriteLiteral("\r\n                                    placeholder=\"Building N.O.\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"form1i\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Building N.O.</label>\r\n                                <i");

WriteLiteral(" class=\"fa fa-times disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                                <em>(required)</em>\r\n                     " +
"       </div>\r\n                            <!-- Street -->\r\n                    " +
"        <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-sign\"");

WriteLiteral("></i>\r\n                                <input");

WriteLiteral(" type=\"name\"");

WriteLiteral(" class=\"form-control validate-name\"");

WriteLiteral(" id=\"form1j\"");

WriteLiteral(" placeholder=\"Street\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"form1j\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Street</label>\r\n                                <i");

WriteLiteral(" class=\"fa fa-times disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                                <em>(required)</em>\r\n                     " +
"       </div>\r\n                            <!-- Postal Code -->\r\n               " +
"             <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-map-pin\"");

WriteLiteral("></i>\r\n                                <input");

WriteLiteral(" type=\"name\"");

WriteLiteral(" class=\"form-control validate-name\"");

WriteLiteral(" id=\"form1k\"");

WriteLiteral("\r\n                                    placeholder=\"Postal Code\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"form1k\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Postal Code</label>\r\n                                <i");

WriteLiteral(" class=\"fa fa-times disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                                <em>(required)</em>\r\n                     " +
"       </div>\r\n                            <!-- Landmark -->\r\n                  " +
"          <div");

WriteLiteral(" class=\"input-style no-borders has-icon validate-field mb-4\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-user\"");

WriteLiteral("></i>\r\n                                <input");

WriteLiteral(" type=\"name\"");

WriteLiteral(" class=\"form-control validate-name\"");

WriteLiteral(" id=\"form1l\"");

WriteLiteral("\r\n                                    placeholder=\"Landmark\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" for=\"form1l\"");

WriteLiteral(" class=\"color-highlight\"");

WriteLiteral(">Landmark</label>\r\n                                <i");

WriteLiteral(" class=\"fa fa-times disabled invalid color-red-dark\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-check disabled valid color-green-dark\"");

WriteLiteral("></i>\r\n                                <em>(required)</em>\r\n                     " +
"       </div>\r\n                            <!-- Schedule -->\r\n                  " +
"          <div");

WriteLiteral(" class=\"content mb-2\"");

WriteLiteral(">\r\n                                <h3");

WriteLiteral(" class=\"mb-n1\"");

WriteLiteral("> <i");

WriteLiteral(" class=\"fa fa-clock\"");

WriteLiteral("></i> Working hours: </h3>\r\n                                <p");

WriteLiteral(" class=\"px-4\"");

WriteLiteral(">you can set up your schedule</p>\r\n                                <table");

WriteLiteral(" class=\"table table-borderless text-center text-black-50 rounded-sm shadow-l\"");

WriteLiteral("\r\n                                    style=\"overflow: hidden;\"");

WriteLiteral(">\r\n                                    <thead>\r\n                                 " +
"       <tr");

WriteLiteral(" class=\"bg-dark-dark\"");

WriteLiteral(">\r\n                                            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"color-white\"");

WriteLiteral(">Day</th>\r\n                                            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"color-white\"");

WriteLiteral(">From</th>\r\n                                            <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"color-white\"");

WriteLiteral(">To</th>\r\n                                        </tr>\r\n                        " +
"            </thead>\r\n                                    <tbody>\r\n             " +
"                           <tr>\r\n                                            <th" +
"");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Saturday</th>\r\n                                            <td");

WriteLiteral(" class=\"color-green-dark\"");

WriteLiteral(">\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            </td>\r\n                           " +
"                 <td>\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            </td>\r\n                           " +
"             </tr>\r\n                                        <tr>\r\n              " +
"                              <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Sunday</th>\r\n                                            <td");

WriteLiteral(" class=\"color-green-dark\"");

WriteLiteral(">\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            </td>\r\n                           " +
"                 <td>\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            </td>\r\n                           " +
"             </tr>\r\n                                        <tr>\r\n              " +
"                              <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Monday</th>\r\n                                            <td");

WriteLiteral(" class=\"color-green-dark\"");

WriteLiteral(">\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            </td>\r\n                           " +
"                 <td>\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            </td>\r\n                           " +
"             </tr>\r\n                                        <tr>\r\n              " +
"                              <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Tuesday</th>\r\n                                            <td");

WriteLiteral(" class=\"color-green-dark\"");

WriteLiteral(">\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            </td>\r\n                           " +
"                 <td>\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            </td>\r\n                           " +
"             </tr>\r\n                                        <tr>\r\n              " +
"                              <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Wednesday</th>\r\n                                            <td");

WriteLiteral(" class=\"color-green-dark\"");

WriteLiteral(">\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            </td>\r\n                           " +
"                 <td>\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            </td>\r\n                           " +
"             </tr>\r\n                                        <tr>\r\n              " +
"                              <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Thursday</th>\r\n                                            <td");

WriteLiteral(" class=\"color-green-dark\"");

WriteLiteral(">\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            </td>\r\n                           " +
"                 <td>\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            </td>\r\n                           " +
"             </tr>\r\n                                        <tr>\r\n              " +
"                              <th");

WriteLiteral(" scope=\"row\"");

WriteLiteral(">Friday</th>\r\n                                            <td");

WriteLiteral(" class=\"color-green-dark\"");

WriteLiteral(">\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                            </td>\r\n                           " +
"                 <td>\r\n                                                <input");

WriteLiteral(" type=\"time\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(@">
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <div");

WriteLiteral(" class=\"tab\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"mt-5 mb-5 text-center\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-check-circle scale-box color-green-dark fa-5x pb-3\"");

WriteLiteral("></i>\r\n                                <h1>Thank you!</h1>\r\n                     " +
"           <p");

WriteLiteral(" class=\"px-3 mb-5\"");

WriteLiteral(">\r\n                                    Your account is ready to use, Enjoy!\r\n    " +
"                            </p>\r\n                            </div>\r\n          " +
"              </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"card-bottomX mt-5 pb-3 d-flex justify-content-evenly\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" class=\"btn btn-m rounded-m bg-orange-dark font-700 text-uppercase\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("\r\n                                id=\"prevBtn\"");

WriteLiteral(" onclick=\"nextPrev(-1)\"");

WriteLiteral(">Previous</button>\r\n                            <button");

WriteLiteral(" class=\"btn btn-m rounded-m bg-orange-dark font-700 text-uppercase\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("\r\n                                id=\"addAddressBtn\"");

WriteLiteral(" onclick=\"\"");

WriteLiteral(">Add Address</button>\r\n                            <button");

WriteLiteral(" class=\"btn btn-m rounded-m bg-orange-dark font-700 text-uppercase\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("\r\n                                id=\"nextBtn\"");

WriteLiteral(" onclick=\"nextPrev(1)\"");

WriteLiteral(">Next</button>\r\n                        </div>\r\n                    </form>\r\n    " +
"            </div>\r\n                <!-- Btns -->\r\n                <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(@">
                    <!-- <div class=""card-bottomX mt-5 pb-3 d-flex justify-content-between"">
                            <a href=""#"" class=""btn btn-m rounded-m bg-orange-dark font-700 text-uppercase""
                            id=""prevBtn"" onclick=""nextPrev(-1)"">Prev Step</a>
                            <a href=""#"" class=""btn btn-m rounded-m bg-orange-dark font-700 text-uppercase""
                            id=""nextBtn"" onclick=""nextPrev(1)"">Next Step</a>
                            <a href=""#"" class=""btn btn-m rounded-m bg-orange-dark font-700 text-uppercase"">Add
                                Address</a>
                            <a href=""#"" class=""btn btn-m rounded-m bg-orange-dark font-700 text-uppercase""
                                id=""submit-btn"">Finish</a>
                        </div> -->

                </div>

            </div>
        </div>
    </div>
    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"Sticky53/scripts/bootstrap.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"Sticky53/scripts/custom.js\"");

WriteLiteral("></script>\r\n    <style>\r\n        .tab {\r\n            display: none;\r\n        }\r\n\r" +
"\n        .step {\r\n            background-color: #e2e5ea;\r\n            color: #ff" +
"f;\r\n        }\r\n    </style>\r\n    <script>\r\n        var currentTab = 0; // Curren" +
"t tab is set to be the first tab (0)\r\n        showTab(currentTab); // Display th" +
"e current tab\r\n\r\n        function showTab(n) {\r\n            // This function wil" +
"l display the specified tab of the form ...\r\n            var x = document.getEle" +
"mentsByClassName(\"tab\");\r\n            x[n].style.display = \"block\";\r\n           " +
" // ... and fix the Previous/Next buttons:\r\n            if (n == 0) {\r\n         " +
"       document.getElementById(\"prevBtn\").style.display = \"none\";\r\n            }" +
" else {\r\n                document.getElementById(\"prevBtn\").style.display = \"inl" +
"ine\";\r\n            }\r\n            // To show the button add address\r\n           " +
" if (n == 1) {\r\n                document.getElementById(\"addAddressBtn\").style.d" +
"isplay = \"inline\";\r\n            } else {\r\n                document.getElementByI" +
"d(\"addAddressBtn\").style.display = \"none\";\r\n            }\r\n            // To sho" +
"w the button add Submit\r\n            if (n == (x.length - 1)) {\r\n               " +
" document.getElementById(\"nextBtn\").innerHTML = \"Submit\";\r\n                // do" +
"cument.getElementById(\"prevBtn\").style.display = \"none\";\r\n            } else {\r\n" +
"                document.getElementById(\"nextBtn\").innerHTML = \"Next\";\r\n        " +
"    }\r\n            // ... and run a function that displays the correct step indi" +
"cator:\r\n            fixStepIndicator(n)\r\n        }\r\n\r\n        function nextPrev(" +
"n) {\r\n            // alert(currentTab);\r\n            // This function will figur" +
"e out which tab to display\r\n            var x = document.getElementsByClassName(" +
"\"tab\");\r\n            // Exit the function if any field in the current tab is inv" +
"alid:\r\n            // if (n == 1 && !validateForm()) return false;\r\n            " +
"// Hide the current tab:\r\n            x[currentTab].style.display = \"none\";\r\n   " +
"         // Increase or decrease the current tab by 1:\r\n            currentTab =" +
" currentTab + n;\r\n            // if you have reached the end of the form... :\r\n " +
"           if (currentTab >= x.length) {\r\n                //...the form gets sub" +
"mitted:\r\n                document.getElementById(\"regForm\").submit();\r\n         " +
"       return false;\r\n            }\r\n            // Otherwise, display the corre" +
"ct tab:\r\n            showTab(currentTab);\r\n        }\r\n\r\n        // function vali" +
"dateForm() {\r\n        //     // This function deals with validation of the form " +
"fields\r\n        //     var x, y, i, valid = true;\r\n        //     x = document.g" +
"etElementsByClassName(\"tab\");\r\n        //     y = x[currentTab].getElementsByTag" +
"Name(\"input\");\r\n        //     // A loop that checks every input field in the cu" +
"rrent tab:\r\n        //     for (i = 0; i < y.length; i++) {\r\n        //         " +
"// If a field is empty...\r\n        //         if (y[i].value == \"\") {\r\n        /" +
"/             // add an \"invalid\" class to the field:\r\n\r\n        //             " +
"// and set the current valid status to false:\r\n        //             valid = fa" +
"lse;\r\n        //         }\r\n        //     }\r\n        //     // If the valid sta" +
"tus is true, mark the step as finished and valid:\r\n        //     if (valid) {\r\n" +
"        //         document.getElementsByClassName(\"step\")[currentTab].className" +
" += \" bg-teal-dark\";\r\n        //     }\r\n        //     return valid; // return t" +
"he valid status\r\n        // }\r\n\r\n        function fixStepIndicator(n) {\r\n       " +
"     // This function removes the \"active\" class of all steps...\r\n            va" +
"r i, x = document.getElementsByClassName(\"step\");\r\n            for (i = 0; i < x" +
".length; i++) {\r\n                x[i].className = x[i].className.replace(\" bg-gr" +
"ay-light\", \"\");\r\n            }\r\n            //... and adds the \"active\" class to" +
" the current step:\r\n            x[n].className += \" bg-orange-dark\";\r\n        }\r" +
"\n    </script>\r\n\r\n\r\n</body>");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class compeletProfileWithoutModalBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
